import {
  ExpeditionVendor,
  Customer,
  Transformer,
  Driver,
  Vehicle,
  Shipment,
  NotificationItem,
  ActivityLogItem,
  User,
} from '@/types';

export const initialUsers: User[] = [
  {
    id: 'usr-admin-01',
    name: 'Jodi Setiawan',
    username: 'JODI',
    password: 'GARMIN',
    email: 'jodi.setiawan@trafo-mkt.co.id',
    role: 'SUPER_ADMIN',
    department: 'Central Logistics & Supply Chain',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-01',
    name: 'Firhan Roebini',
    email: 'firhan.roebini@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — General Manager',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-02',
    name: 'Lismaya Sari',
    email: 'lismaya.sari@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Supervisor',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-03',
    name: 'Willi Syukran',
    email: 'willi.syukran@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Unit Manager',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-04',
    name: 'Jani Susilowati',
    email: 'jani.susilowati@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Unit Manager',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-05',
    name: 'I Wayan Eva Verdiana',
    email: 'wayan.verdiana@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Sales Engineer',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-06',
    name: 'Shevira Indraswari',
    email: 'shevira.indraswari@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Sales Engineer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-07',
    name: 'Cassa Vita Sari',
    email: 'cassa.vita@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Sales Engineer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-08',
    name: 'Kresna Budi Prasetya',
    email: 'kresna.budi@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Sales Engineer',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-09',
    name: 'Elnira Ainunnisa',
    email: 'elnira.ainunnisa@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Sales Engineer',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-10',
    name: 'Danny Teja',
    email: 'danny.teja@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Sales Engineer',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-11',
    name: 'Permata Sari Telaumbanua',
    email: 'permata.telaumbanua@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Officer',
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-12',
    name: 'Yulianih',
    email: 'yulianih@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Officer',
    avatar: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-13',
    name: 'Prestysari Dinda Musthika',
    email: 'prestysari.musthika@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Officer',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-14',
    name: 'Ahmad Nurseha',
    email: 'ahmad.nurseha@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Officer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-15',
    name: 'Jonathan Simanulang',
    email: 'jonathan.simanulang@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Officer',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-16',
    name: 'Yogi Rahmadani Saputra',
    email: 'yogi.saputra@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Officer',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-17',
    name: 'Luthfan Andi Pradana',
    email: 'luthfan.pradana@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Officer',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-18',
    name: 'Aurellia Layla Mahani',
    email: 'aurellia.mahani@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Officer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-19',
    name: 'Jhody Aido Saut Hutagalung',
    email: 'jhody.hutagalung@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Officer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-20',
    name: 'Keysha Zara Alifa Panjaitan',
    email: 'keysha.panjaitan@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Officer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-21',
    name: 'M Dhayfullah Lazuardi',
    email: 'm.lazuardi@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Admin',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-22',
    name: 'Vallysia Salsabilla Putri',
    email: 'vallysia.putri@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Admin',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-23',
    name: 'Komang Bagus Lanang Prabawa',
    email: 'komang.prabawa@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-24',
    name: 'Gregorius Harkristyono Daru Sesotya',
    email: 'gregorius.sesotya@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Admin',
    avatar: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-mkt-25',
    name: 'Muhamad Fahrul Alamsyah',
    email: 'muhamad.alamsyah@trafo-mkt.co.id',
    role: 'MARKETING',
    department: 'Marketing — Admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-ven-01',
    name: 'Hendra Gunawan (Samudera)',
    email: 'ops@samuderatrans.co.id',
    role: 'VENDOR',
    vendorId: 'ven-01',
    department: 'Dispatch & Fleet Operations',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-ven-02',
    name: 'Rahmat Hidayat (Iron Logistics)',
    email: 'dispatch@ironheavyhaul.co.id',
    role: 'VENDOR',
    vendorId: 'ven-02',
    department: 'Heavy Haul Ops',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-ven-03',
    name: 'Budi Santoso (Dunex Cargo)',
    email: 'tracking@dunexcargo.co.id',
    role: 'VENDOR',
    vendorId: 'ven-03',
    department: 'Operations',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-ven-04',
    name: 'Agus Setiawan (Pos Logistik)',
    email: 'heavyhaul@poslogistics.co.id',
    role: 'VENDOR',
    vendorId: 'ven-04',
    department: 'Industrial Projects',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-ven-05',
    name: 'Joko Prabowo (Siba Surya)',
    email: 'dispatch@sibasurya.com',
    role: 'VENDOR',
    vendorId: 'ven-05',
    department: 'Heavy Freight',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-ven-06',
    name: 'Teguh Wicaksono (Puninar Transport)',
    email: 'control@puninar.com',
    role: 'VENDOR',
    vendorId: 'ven-06',
    department: 'Control Tower',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-ven-07',
    name: 'Denny Kurniawan (Lookman Djaja)',
    email: 'heavy@lookmandjaja.co.id',
    role: 'VENDOR',
    vendorId: 'ven-07',
    department: 'Operations',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-ven-08',
    name: 'Siti Rahma (Kamadjaja)',
    email: 'industrial@kamadjaja.com',
    role: 'VENDOR',
    vendorId: 'ven-08',
    department: 'Logistics',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-ven-09',
    name: 'Fauzi Rahman (CKB Logistics)',
    email: 'project@ckb.co.id',
    role: 'VENDOR',
    vendorId: 'ven-09',
    department: 'Project Logistics',
    avatar: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-ven-10',
    name: 'Arif Wibowo (Berdikari Bahari)',
    email: 'ops@berdikarilog.co.id',
    role: 'VENDOR',
    vendorId: 'ven-10',
    department: 'Transport Ops',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=120&auto=format&fit=crop&q=80',
  },
];

export const initialVendors: ExpeditionVendor[] = [
  {
    id: 'ven-01',
    name: 'PT Samudera Perdana Selaras',
    code: 'SPS-LOG',
    pic: 'Hendra Gunawan',
    phone: '+62 811-9871-2201',
    email: 'ops@samuderatrans.co.id',
    address: 'Jl. Kali Besar Barat No. 43, Roa Malaka, Tambora, Jakarta Barat',
    totalShipments: 48,
    onTimeRate: 97.9,
    delayedCount: 1,
    avgDeliveryHours: 26.4,
    podCompletionRate: 100,
    active: true,
    rating: 4.9,
    fleetCount: 32,
    badge: 'Tier 1 Prime Partner',
  },
  {
    id: 'ven-02',
    name: 'PT Iron Heavy Haulage',
    code: 'IRN-HAUL',
    pic: 'Rahmat Hidayat',
    phone: '+62 812-3344-9081',
    email: 'dispatch@ironheavyhaul.co.id',
    address: 'Kawasan Industri MM2100 Blok C-8, Cikarang Barat, Bekasi',
    totalShipments: 42,
    onTimeRate: 95.2,
    delayedCount: 2,
    avgDeliveryHours: 28.1,
    podCompletionRate: 97.6,
    active: true,
    rating: 4.8,
    fleetCount: 24,
    badge: 'Specialist Lowbed',
  },
  {
    id: 'ven-03',
    name: 'PT Dunex Heavy Cargo Logistics',
    code: 'DNX-CRG',
    pic: 'Budi Santoso',
    phone: '+62 813-8890-1123',
    email: 'tracking@dunexcargo.co.id',
    address: 'Jl. Pelabuhan Tanjung Priok No. 12, Jakarta Utara',
    totalShipments: 39,
    onTimeRate: 94.8,
    delayedCount: 2,
    avgDeliveryHours: 29.5,
    podCompletionRate: 95.0,
    active: true,
    rating: 4.7,
    fleetCount: 28,
  },
  {
    id: 'ven-04',
    name: 'PT Pos Logistik Indonesia',
    code: 'POS-LOG',
    pic: 'Agus Setiawan',
    phone: '+62 815-4422-7711',
    email: 'heavyhaul@poslogistics.co.id',
    address: 'Gedung Pos Ibukota Lt. 2, Jl. Lapangan Banteng Utara No. 1, Jakarta',
    totalShipments: 35,
    onTimeRate: 91.4,
    delayedCount: 3,
    avgDeliveryHours: 32.0,
    podCompletionRate: 94.2,
    active: true,
    rating: 4.5,
    fleetCount: 40,
    badge: 'National Coverage',
  },
  {
    id: 'ven-05',
    name: 'PT Siba Surya Heavy Cargo',
    code: 'SBA-SRY',
    pic: 'Joko Prabowo',
    phone: '+62 812-7788-0912',
    email: 'dispatch@sibasurya.com',
    address: 'Jl. Terboyo Industri Timur No. 1, Genuk, Semarang, Jawa Tengah',
    totalShipments: 44,
    onTimeRate: 95.5,
    delayedCount: 2,
    avgDeliveryHours: 27.8,
    podCompletionRate: 98.0,
    active: true,
    rating: 4.8,
    fleetCount: 55,
    badge: 'Pantura Heavy Hauler',
  },
  {
    id: 'ven-06',
    name: 'PT Puninar Heavy Transport',
    code: 'PNR-TRN',
    pic: 'Teguh Wicaksono',
    phone: '+62 818-0912-3344',
    email: 'control@puninar.com',
    address: 'Jl. Raya Cakung Cilincing Km. 1.5, Jakarta Timur',
    totalShipments: 37,
    onTimeRate: 91.9,
    delayedCount: 3,
    avgDeliveryHours: 30.5,
    podCompletionRate: 92.5,
    active: true,
    rating: 4.6,
    fleetCount: 30,
  },
  {
    id: 'ven-07',
    name: 'PT Lookman Djaja Logistics',
    code: 'LKM-DJJ',
    pic: 'Denny Kurniawan',
    phone: '+62 811-2299-8800',
    email: 'heavy@lookmandjaja.co.id',
    address: 'Kawasan Industri SIER, Rungkut Industri Raya No. 18, Surabaya',
    totalShipments: 31,
    onTimeRate: 90.3,
    delayedCount: 3,
    avgDeliveryHours: 33.2,
    podCompletionRate: 91.0,
    active: true,
    rating: 4.4,
    fleetCount: 22,
  },
  {
    id: 'ven-08',
    name: 'PT Kamadjaja Logistics',
    code: 'KMJ-LOG',
    pic: 'Siti Rahma',
    phone: '+62 812-9900-3341',
    email: 'industrial@kamadjaja.com',
    address: 'Kargo Kompartemen Timur, Pelabuhan Tanjung Perak, Surabaya',
    totalShipments: 28,
    onTimeRate: 89.3,
    delayedCount: 3,
    avgDeliveryHours: 34.0,
    podCompletionRate: 89.5,
    active: true,
    rating: 4.3,
    fleetCount: 20,
  },
  {
    id: 'ven-09',
    name: 'PT Cipta Krida Bahari (CKB Logistics)',
    code: 'CKB-LOG',
    pic: 'Fauzi Rahman',
    phone: '+62 813-1122-3345',
    email: 'project@ckb.co.id',
    address: 'Gedung TMT 1 Lt. 7, Jl. Cilandak KKO No. 1, Jakarta Selatan',
    totalShipments: 33,
    onTimeRate: 93.9,
    delayedCount: 2,
    avgDeliveryHours: 29.8,
    podCompletionRate: 96.0,
    active: true,
    rating: 4.7,
    fleetCount: 26,
    badge: 'Inter-Island Multimodal',
  },
  {
    id: 'ven-10',
    name: 'PT Berdikari Pondok Bahari',
    code: 'BDK-LOG',
    pic: 'Arif Wibowo',
    phone: '+62 812-4455-6677',
    email: 'ops@berdikarilog.co.id',
    address: 'Jl. Marunda Makmur No. 88, Cilincing, Jakarta Utara',
    totalShipments: 24,
    onTimeRate: 87.5,
    delayedCount: 3,
    avgDeliveryHours: 36.5,
    podCompletionRate: 87.5,
    active: true,
    rating: 4.1,
    fleetCount: 18,
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-01',
    companyName: 'PT PLN (Persero) UID Jawa Barat — GI Cikarang Utama',
    customerPic: 'Ir. Agus Pratama, S.T.',
    phone: '+62 812-2233-4455',
    email: 'agus.pratama@pln.co.id',
    address: 'Gardu Induk Cikarang Utama 150kV, Jl. Industri Raya No. 4, Cikarang',
    city: 'Bekasi',
    province: 'Jawa Barat',
    postalCode: '17530',
    latitude: -6.3121,
    longitude: 107.1352,
  },
  {
    id: 'cust-02',
    companyName: 'PT PLN (Persero) UIP JBT — GI Bandung Selatan',
    customerPic: 'Rizki Nurhidayat',
    phone: '+62 813-9081-7722',
    email: 'rizki.pln@pln.co.id',
    address: 'Komplek Gardu Induk Bandung Selatan 150/20kV, Moh Toha Km 6.5',
    city: 'Bandung',
    province: 'Jawa Barat',
    postalCode: '40256',
    latitude: -6.9744,
    longitude: 107.6087,
  },
  {
    id: 'cust-03',
    companyName: 'PT Pertamina Hulu Rokan — Duri Gathering Station',
    customerPic: 'Muhammad Fadhil',
    phone: '+62 811-7654-3210',
    email: 'fadhil.phr@pertamina.com',
    address: 'Main Substation GS-4, Camp Duri Km 12, Mandau, Bengkalis',
    city: 'Duri',
    province: 'Riau',
    postalCode: '28784',
    latitude: 1.2721,
    longitude: 101.2183,
  },
  {
    id: 'cust-04',
    companyName: 'PT Krakatau Posco — Cilegon Integrated Complex',
    customerPic: 'Wahyudi Santoso',
    phone: '+62 812-9800-4411',
    email: 'wahyudi.s@krakatauposco.co.id',
    address: 'Substation B Furnace, Kawasan Industri Krakatau Steel, Jl. Asia Raya',
    city: 'Cilegon',
    province: 'Banten',
    postalCode: '42435',
    latitude: -6.0022,
    longitude: 106.0125,
  },
  {
    id: 'cust-05',
    companyName: 'PT Semen Indonesia (Persero) Tbk — Pabrik Tuban',
    customerPic: 'Tri Wahyono',
    phone: '+62 813-3321-6543',
    email: 'tri.wahyono@sig.id',
    address: 'Gardu Induk Pabrik Tuban 4, Desa Sumberarum, Kerek',
    city: 'Tuban',
    province: 'Jawa Timur',
    postalCode: '62356',
    latitude: -6.8988,
    longitude: 111.9542,
  },
  {
    id: 'cust-06',
    companyName: 'PT Kawasan Industri Jababeka Tbk — Substation Cikarang',
    customerPic: 'Haryanto Gunawan',
    phone: '+62 815-1100-2233',
    email: 'haryanto@jababeka.com',
    address: 'Power Plant & Substation Estate 3, Jababeka Industrial Park',
    city: 'Bekasi',
    province: 'Jawa Barat',
    postalCode: '17550',
    latitude: -6.2891,
    longitude: 107.1623,
  },
  {
    id: 'cust-07',
    companyName: 'PT Vale Indonesia Tbk — Sorowako Smelter Substation',
    customerPic: 'Andi Mappanyukki',
    phone: '+62 811-4400-9898',
    email: 'andi.m@vale.com',
    address: 'Smelter Substation #3, Jl. Inco, Magani, Nuha',
    city: 'Luwu Timur',
    province: 'Sulawesi Selatan',
    postalCode: '92984',
    latitude: -2.5358,
    longitude: 121.3533,
  },
  {
    id: 'cust-08',
    companyName: 'PT Amman Mineral Nusa Tenggara — Batu Hijau Power Station',
    customerPic: 'Kadek Sutama',
    phone: '+62 819-0988-7766',
    email: 'kadek.s@amman.co.id',
    address: 'Main Step-Up Substation Batu Hijau, Sekongkang',
    city: 'Sumbawa Barat',
    province: 'Nusa Tenggara Barat',
    postalCode: '84457',
    latitude: -8.9667,
    longitude: 116.8667,
  },
];

export const initialTransformers: Transformer[] = [
  {
    id: 'trf-01',
    transformerNumber: 'TRF-3000-001',
    serialNumber: 'SN-2026-XF9910',
    type: 'Step-Down Power Transformer (Oil Immersed)',
    capacityKVA: 3000,
    weightKg: 14200,
    dimensions: { length: 3450, width: 2150, height: 2980 },
    oilType: 'Nynas Nytro 4000X Inhibited',
    voltageRating: '20 kV / 400 V',
    productionCompletionDate: '2026-08-20',
    coolingType: 'ONAF (Oil Natural Air Forced)',
  },
  {
    id: 'trf-02',
    transformerNumber: 'TRF-2500-002',
    serialNumber: 'SN-2026-XF8821',
    type: 'Three-Phase Step-Down Transformer',
    capacityKVA: 2500,
    weightKg: 11800,
    dimensions: { length: 3100, width: 1950, height: 2750 },
    oilType: 'Shell Diala S4 ZX-I',
    voltageRating: '20 kV / 400 V',
    productionCompletionDate: '2026-08-22',
    coolingType: 'ONAN (Oil Natural Air Natural)',
  },
  {
    id: 'trf-03',
    transformerNumber: 'TRF-2500-003',
    serialNumber: 'SN-2026-XF8822',
    type: 'Cast Resin Dry Type Transformer',
    capacityKVA: 2500,
    weightKg: 9600,
    dimensions: { length: 2800, width: 1650, height: 2400 },
    oilType: 'None (Dry Type Class F)',
    voltageRating: '20 kV / 400 V',
    productionCompletionDate: '2026-08-23',
    coolingType: 'AN (Air Natural)',
  },
  {
    id: 'trf-04',
    transformerNumber: 'TRF-1600-004',
    serialNumber: 'SN-2026-XF7101',
    type: 'Distribution Transformer Heavy Duty',
    capacityKVA: 1600,
    weightKg: 7800,
    dimensions: { length: 2600, width: 1550, height: 2200 },
    oilType: 'Pertamina Trafo Oil Uninhibited',
    voltageRating: '20 kV / 400 V',
    productionCompletionDate: '2026-08-25',
    coolingType: 'ONAN',
  },
  {
    id: 'trf-05',
    transformerNumber: 'TRF-1600-005',
    serialNumber: 'SN-2026-XF7102',
    type: 'Distribution Transformer Hermetically Sealed',
    capacityKVA: 1600,
    weightKg: 7650,
    dimensions: { length: 2580, width: 1520, height: 2180 },
    oilType: 'Shell Diala S4 ZX-I',
    voltageRating: '20 kV / 400 V',
    productionCompletionDate: '2026-08-26',
    coolingType: 'ONAN',
  },
  {
    id: 'trf-06',
    transformerNumber: 'TRF-1000-006',
    serialNumber: 'SN-2026-XF5001',
    type: 'Compact Substation Transformer',
    capacityKVA: 1000,
    weightKg: 5200,
    dimensions: { length: 2200, width: 1350, height: 1950 },
    oilType: 'Nynas Nytro 4000X',
    voltageRating: '20 kV / 400 V',
    productionCompletionDate: '2026-08-27',
    coolingType: 'ONAN',
  },
  {
    id: 'trf-07',
    transformerNumber: 'TRF-1000-007',
    serialNumber: 'SN-2026-XF5002',
    type: 'Industrial Step-Down Transformer',
    capacityKVA: 1000,
    weightKg: 5150,
    dimensions: { length: 2180, width: 1340, height: 1940 },
    oilType: 'Pertamina Trafo Oil',
    voltageRating: '20 kV / 400 V',
    productionCompletionDate: '2026-08-28',
    coolingType: 'ONAN',
  },
  {
    id: 'trf-08',
    transformerNumber: 'TRF-500-008',
    serialNumber: 'SN-2026-XF3101',
    type: 'Pole / Pad Mounted Transformer',
    capacityKVA: 500,
    weightKg: 3100,
    dimensions: { length: 1800, width: 1100, height: 1650 },
    oilType: 'Mineral Oil IEC 60296',
    voltageRating: '20 kV / 400 V',
    productionCompletionDate: '2026-08-29',
    coolingType: 'ONAN',
  },
  {
    id: 'trf-09',
    transformerNumber: 'TRF-500-009',
    serialNumber: 'SN-2026-XF3102',
    type: 'Auxiliary Service Transformer',
    capacityKVA: 500,
    weightKg: 3050,
    dimensions: { length: 1780, width: 1090, height: 1640 },
    oilType: 'Mineral Oil IEC 60296',
    voltageRating: '20 kV / 400 V',
    productionCompletionDate: '2026-08-30',
    coolingType: 'ONAN',
  },
  {
    id: 'trf-10',
    transformerNumber: 'TRF-3000-010',
    serialNumber: 'SN-2026-XF9911',
    type: 'Heavy Industrial Furnace Transformer',
    capacityKVA: 3000,
    weightKg: 14800,
    dimensions: { length: 3500, width: 2200, height: 3050 },
    oilType: 'FR3 Natural Ester Fluid',
    voltageRating: '33 kV / 690 V',
    productionCompletionDate: '2026-08-31',
    coolingType: 'OFAF (Oil Forced Air Forced)',
  },
];

export const initialDrivers: Driver[] = [
  {
    id: 'drv-01',
    vendorId: 'ven-01',
    name: 'Sutrisno Waluyo',
    phone: '+62 812-9011-8841',
    simNumber: '9201-1823-9901',
    simType: 'BII Umum',
    emergencyContact: 'Ibu Warsini (+62 813-8877-0012)',
    status: 'On Duty',
  },
  {
    id: 'drv-02',
    vendorId: 'ven-02',
    name: 'Yanto Subagyo',
    phone: '+62 813-4455-7799',
    simNumber: '8810-2291-7712',
    simType: 'BII Umum',
    emergencyContact: 'Ibu Ningsih (+62 812-7711-2290)',
    status: 'On Duty',
  },
  {
    id: 'drv-03',
    vendorId: 'ven-03',
    name: 'Bambang Irawan',
    phone: '+62 815-6677-8899',
    simNumber: '7721-0091-8834',
    simType: 'BII Umum',
    emergencyContact: 'Slamet Irawan (+62 813-2211-4455)',
    status: 'On Duty',
  },
  {
    id: 'drv-04',
    vendorId: 'ven-04',
    name: 'Dedi Kurniawan',
    phone: '+62 818-9900-1122',
    simNumber: '6610-8822-1145',
    simType: 'BII Umum',
    emergencyContact: 'Ibu Erna (+62 815-7788-9900)',
    status: 'Available',
  },
  {
    id: 'drv-05',
    vendorId: 'ven-05',
    name: 'Kuswanto Mulyadi',
    phone: '+62 812-1122-4466',
    simNumber: '5519-3344-9912',
    simType: 'BII Umum',
    emergencyContact: 'Ibu Supartin (+62 813-5566-7788)',
    status: 'On Duty',
  },
  {
    id: 'drv-06',
    vendorId: 'ven-06',
    name: 'Hadi Sucipto',
    phone: '+62 813-7788-9900',
    simNumber: '4418-2233-8891',
    simType: 'BII Umum',
    emergencyContact: 'Mas Joko (+62 812-3344-5566)',
    status: 'On Duty',
  },
  {
    id: 'drv-07',
    vendorId: 'ven-07',
    name: 'Ahmad Faisal',
    phone: '+62 811-3322-1100',
    simNumber: '3317-1122-7789',
    simType: 'BII Umum',
    emergencyContact: 'Ibu Halimah (+62 816-7788-9900)',
    status: 'Available',
  },
  {
    id: 'drv-08',
    vendorId: 'ven-08',
    name: 'Sugeng Riyadi',
    phone: '+62 812-4455-8811',
    simNumber: '2216-9900-6678',
    simType: 'BII Umum',
    emergencyContact: 'Ibu Siti (+62 813-9900-1122)',
    status: 'On Duty',
  },
  {
    id: 'drv-09',
    vendorId: 'ven-09',
    name: 'Wawan Gunawan',
    phone: '+62 813-8899-0011',
    simNumber: '1115-8899-5567',
    simType: 'BII Umum',
    emergencyContact: 'Bapak Roni (+62 812-6677-8899)',
    status: 'On Duty',
  },
  {
    id: 'drv-10',
    vendorId: 'ven-10',
    name: 'Supardi Hartono',
    phone: '+62 815-2233-4455',
    simNumber: '9914-7788-4456',
    simType: 'BII Umum',
    emergencyContact: 'Ibu Lastri (+62 818-4455-6677)',
    status: 'Available',
  },
];

export const initialVehicles: Vehicle[] = [
  {
    id: 'veh-01',
    vendorId: 'ven-01',
    plateNumber: 'B 9821 UXT',
    type: 'Tronton Lowbed',
    brand: 'Hino Profia 700 6x4',
    model: 'Profia Heavy Hauler 480HP',
    capacityTons: 45,
    dimensions: { length: 14.5, width: 3.0, height: 1.1 },
    gpsId: 'GPS-SPS-9821',
    status: 'In Transit',
  },
  {
    id: 'veh-02',
    vendorId: 'ven-02',
    plateNumber: 'B 9204 TYN',
    type: 'Multi-Axle Heavy Hauler',
    brand: 'Volvo FH16 700',
    model: 'Goldhofer Multi-Axle Platform',
    capacityTons: 80,
    dimensions: { length: 16.2, width: 3.2, height: 1.0 },
    gpsId: 'GPS-IRN-9204',
    status: 'In Transit',
  },
  {
    id: 'veh-03',
    vendorId: 'ven-03',
    plateNumber: 'B 9155 PQR',
    type: 'Trailer Flatbed 40ft',
    brand: 'Scania R580 6x4',
    model: 'Heavy Duty Flatbed Container/Cargo',
    capacityTons: 38,
    dimensions: { length: 12.8, width: 2.6, height: 1.5 },
    gpsId: 'GPS-DNX-9155',
    status: 'In Transit',
  },
  {
    id: 'veh-04',
    vendorId: 'ven-04',
    plateNumber: 'B 9301 POS',
    type: 'Tronton Lowbed',
    brand: 'Hino 500 FL 260 JW',
    model: 'Lowbed Platform Heavy Machinery',
    capacityTons: 30,
    dimensions: { length: 13.0, width: 2.8, height: 1.2 },
    gpsId: 'GPS-POS-9301',
    status: 'Ready',
  },
  {
    id: 'veh-05',
    vendorId: 'ven-05',
    plateNumber: 'H 8812 BA',
    type: 'Tronton Lowbed',
    brand: 'Mercedes-Benz Actros 3340',
    model: 'Actros 6x4 Lowbed Semi-Trailer',
    capacityTons: 40,
    dimensions: { length: 14.0, width: 2.9, height: 1.15 },
    gpsId: 'GPS-SBA-8812',
    status: 'In Transit',
  },
  {
    id: 'veh-06',
    vendorId: 'ven-06',
    plateNumber: 'B 9744 UZZ',
    type: 'Tronton Lowbed',
    brand: 'Hino 700 Series',
    model: 'Lowbed Hauler 420HP',
    capacityTons: 35,
    dimensions: { length: 13.5, width: 2.85, height: 1.2 },
    gpsId: 'GPS-PNR-9744',
    status: 'In Transit',
  },
  {
    id: 'veh-07',
    vendorId: 'ven-07',
    plateNumber: 'L 8102 QA',
    type: 'Trailer Flatbed 40ft',
    brand: 'Volvo FM440',
    model: 'Flatbed Heavy Deck',
    capacityTons: 36,
    dimensions: { length: 12.5, width: 2.6, height: 1.45 },
    gpsId: 'GPS-LKM-8102',
    status: 'Ready',
  },
  {
    id: 'veh-08',
    vendorId: 'ven-08',
    plateNumber: 'L 9021 UU',
    type: 'Tronton Lowbed',
    brand: 'Scania P410 6x4',
    model: 'Lowbed Drop Deck',
    capacityTons: 34,
    dimensions: { length: 13.2, width: 2.8, height: 1.25 },
    gpsId: 'GPS-KMJ-9021',
    status: 'In Transit',
  },
  {
    id: 'veh-09',
    vendorId: 'ven-09',
    plateNumber: 'B 9481 CKB',
    type: 'Multi-Axle Heavy Hauler',
    brand: 'MAN TGX 33.540',
    model: 'Hydraulic Multi-Axle 6-Row',
    capacityTons: 75,
    dimensions: { length: 15.8, width: 3.2, height: 1.05 },
    gpsId: 'GPS-CKB-9481',
    status: 'In Transit',
  },
  {
    id: 'veh-10',
    vendorId: 'ven-10',
    plateNumber: 'B 9550 BRD',
    type: 'Tronton Lowbed',
    brand: 'Hino Profia 500',
    model: 'Drop Frame Lowbed',
    capacityTons: 32,
    dimensions: { length: 13.0, width: 2.75, height: 1.3 },
    gpsId: 'GPS-BDK-9550',
    status: 'Ready',
  },
];

export const initialShipments: Shipment[] = [
  {
    id: 'SHP-2026-0801',
    deliveryOrderNo: 'DO-2026-0941',
    salesOrderNo: 'SO-2026-0412',
    poNumber: 'PO-PLN-JBT-2026-88',
    transformerId: 'trf-01',
    transformer: initialTransformers[0],
    customerId: 'cust-01',
    customer: initialCustomers[0],
    vendorId: 'ven-01',
    vendor: initialVendors[0],
    driverId: 'drv-01',
    driver: initialDrivers[0],
    vehicleId: 'veh-01',
    vehicle: initialVehicles[0],
    currentStatus: 'IN_TRANSIT',
    shipmentDate: '2026-09-03',
    departureDate: '2026-09-03 08:30',
    expectedDeliveryDate: '2026-09-04 16:00',
    originCity: 'Tangerang',
    originAddress: 'PT. SYMPHOS ELECTRIC, Jl. Raya Agarindo No. 10, Kel. Bunder, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    destinationCity: 'Bekasi',
    destinationAddress: 'Gardu Induk Cikarang Utama 150kV, Jl. Industri Raya No. 4, Cikarang',
    currentLocation: {
      city: 'Karawang Timur',
      province: 'Jawa Barat',
      landmark: 'Rest Area KM 57 Tol Jakarta-Cikampek',
      lat: -6.3452,
      lng: 107.3214,
      speedKmH: 38,
      lastUpdatedAt: '2026-09-04 01:15',
    },
    distanceKm: 85,
    remainingKm: 28,
    isDelayed: false,
    preDeliveryInspection: {
      bushingCondition: 'Good',
      radiatorCondition: 'Good',
      conservatorCondition: 'Good',
      accessoriesCondition: 'Complete',
      oilLeakage: false,
      rustOrDamage: false,
      overallCondition: 'Good',
      inspectedBy: 'QC Inspector Rian Wardhana',
      inspectedAt: '2026-09-03 07:45',
      notes: 'Trafo dalam kondisi prima, nitrogen purge terpasang aman, sealing cap bushing lengkap.',
      photos: [
        { title: 'Tampak Depan & Bushing', url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80' },
        { title: 'Radiator Fin Check', url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=500&auto=format&fit=crop&q=80' },
        { title: 'Conservator & Silicagel', url: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=500&auto=format&fit=crop&q=80' },
        { title: 'Lashing ke Lowbed Deck', url: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=500&auto=format&fit=crop&q=80' },
      ],
    },
    trackingHistory: [
      {
        id: 'tr-01',
        step: 1,
        status: 'SHIPMENT_CREATED',
        title: 'Shipment Order Dibuat',
        timestamp: '2026-09-02 14:00',
        location: 'Sistem Pusat Cikarang',
        updatedBy: 'Jodi Setiawan (Admin)',
        role: 'SUPER_ADMIN',
        notes: 'Delivery Order DO-2026-0941 dialokasikan ke PT Samudera Perdana Selaras.',
      },
      {
        id: 'tr-02',
        step: 2,
        status: 'WAITING_PICKUP',
        title: 'Menunggu Pengambilan Vendor',
        timestamp: '2026-09-02 16:30',
        location: 'Pool SPS Jakarta',
        updatedBy: 'Hendra Gunawan (Vendor SPS)',
        role: 'VENDOR',
        notes: 'Vendor konfirmasi kesiapan unit Lowbed Hino Profia B 9821 UXT.',
      },
      {
        id: 'tr-03',
        step: 3,
        status: 'VEHICLE_ASSIGNED',
        title: 'Kendaraan Dialokasikan',
        timestamp: '2026-09-02 17:00',
        location: 'Pool SPS Jakarta',
        updatedBy: 'Hendra Gunawan (Vendor SPS)',
        role: 'VENDOR',
        notes: 'Unit Tronton Lowbed B 9821 UXT kapasitas 45 Ton dialokasikan.',
      },
      {
        id: 'tr-04',
        step: 4,
        status: 'DRIVER_ASSIGNED',
        title: 'Driver Ditugaskan',
        timestamp: '2026-09-02 17:30',
        location: 'Pool SPS Jakarta',
        updatedBy: 'Hendra Gunawan (Vendor SPS)',
        role: 'VENDOR',
        notes: 'Driver Sutrisno Waluyo (SIM BII Umum) ditugaskan mengawal rute.',
      },
      {
        id: 'tr-05',
        step: 5,
        status: 'PICKUP',
        title: 'Tiba di Pabrik Pengirim',
        timestamp: '2026-09-03 07:15',
        location: 'Factory Gate 2 Cikarang',
        updatedBy: 'Sutrisno Waluyo (Driver)',
        role: 'VENDOR',
        notes: 'Truk tiba di staging loading bay, persiapan inspeksi pre-delivery.',
      },
      {
        id: 'tr-06',
        step: 6,
        status: 'LOADED',
        title: 'Trafo Dimuat & Dilashing',
        timestamp: '2026-09-03 08:00',
        location: 'Loading Bay 1 Factory Cikarang',
        updatedBy: 'Sutrisno Waluyo (Driver)',
        role: 'VENDOR',
        notes: 'Pemuatan menggunakan crane 50 Ton. Lashing 8 rantai grade 80 selesai.',
      },
      {
        id: 'tr-07',
        step: 7,
        status: 'DEPARTED',
        title: 'Berangkat Menuju Tujuan',
        timestamp: '2026-09-03 08:30',
        location: 'Gerbang Pabrik Cikarang',
        updatedBy: 'Sutrisno Waluyo (Driver)',
        role: 'VENDOR',
        notes: 'Berangkat dengan pengawalan mobil escort roda empat.',
      },
      {
        id: 'tr-08',
        step: 8,
        status: 'IN_TRANSIT',
        title: 'Dalam Perjalanan (In Transit)',
        timestamp: '2026-09-04 01:15',
        location: 'KM 57 Tol Japek',
        updatedBy: 'Sutrisno Waluyo (Driver)',
        role: 'VENDOR',
        notes: 'Istirahat berkala pengecekan ketegangan rantai lashing. Kondisi trafo stabil aman.',
      },
    ],
    documents: [
      { id: 'doc-01', name: 'Surat_Jalan_DO-2026-0941.pdf', type: 'Surat Jalan', fileSize: '2.4 MB', url: '#', uploadedAt: '2026-09-03 08:10', uploadedBy: 'SPS Dispatch' },
      { id: 'doc-02', name: 'Delivery_Order_PLN.pdf', type: 'Delivery Order', fileSize: '1.8 MB', url: '#', uploadedAt: '2026-09-03 08:12', uploadedBy: 'Internal Logistics' },
      { id: 'doc-03', name: 'KIR_STNK_B9821UXT.pdf', type: 'STNK / KIR', fileSize: '1.2 MB', url: '#', uploadedAt: '2026-09-02 17:15', uploadedBy: 'SPS Fleet' },
      { id: 'doc-04', name: 'Asuransi_Marine_Cargo.pdf', type: 'Asuransi Pengiriman', fileSize: '3.1 MB', url: '#', uploadedAt: '2026-09-02 18:00', uploadedBy: 'Finance' },
    ],
    photos: [
      { id: 'ph-01', title: 'Inspeksi Bushing & Terminal', category: 'Pre-Inspection', url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80', timestamp: '2026-09-03 07:45', location: 'Factory Loading Bay', uploadedBy: 'QC Rian' },
      { id: 'ph-02', title: 'Lashing Rantai Pengaman', category: 'Loading', url: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&auto=format&fit=crop&q=80', timestamp: '2026-09-03 08:15', location: 'Factory Gate', uploadedBy: 'Driver Sutrisno' },
      { id: 'ph-03', title: 'Pengecekan Rest Area KM 57', category: 'In Transit', url: 'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&auto=format&fit=crop&q=80', timestamp: '2026-09-04 01:10', location: 'KM 57 Tol Japek', uploadedBy: 'Driver Sutrisno' },
    ],
    activityLogs: [
      { id: 'act-01', user: 'Jodi Setiawan', role: 'SUPER_ADMIN', action: 'Membuat shipment baru SHP-2026-0801', timestamp: '2026-09-02 14:00' },
      { id: 'act-02', user: 'Hendra Gunawan', role: 'VENDOR', action: 'Menetapkan Truk B 9821 UXT dan Driver Sutrisno', timestamp: '2026-09-02 17:30' },
      { id: 'act-03', user: 'Sutrisno Waluyo', role: 'VENDOR', action: 'Mengunggah checklist Pre-Delivery Inspection (Kondisi Good)', timestamp: '2026-09-03 07:50' },
      { id: 'act-04', user: 'Sutrisno Waluyo', role: 'VENDOR', action: 'Memperbarui status ke IN_TRANSIT dari KM 57 Tol Japek', timestamp: '2026-09-04 01:15' },
    ],
  },
  {
    id: 'SHP-2026-0802',
    deliveryOrderNo: 'DO-2026-0942',
    salesOrderNo: 'SO-2026-0415',
    poNumber: 'PO-PLN-BDG-2026-04',
    transformerId: 'trf-02',
    transformer: initialTransformers[1],
    customerId: 'cust-02',
    customer: initialCustomers[1],
    vendorId: 'ven-02',
    vendor: initialVendors[1],
    driverId: 'drv-02',
    driver: initialDrivers[1],
    vehicleId: 'veh-02',
    vehicle: initialVehicles[1],
    currentStatus: 'IN_TRANSIT',
    shipmentDate: '2026-09-03',
    departureDate: '2026-09-03 09:00',
    expectedDeliveryDate: '2026-09-04 14:00',
    originCity: 'Tangerang',
    originAddress: 'PT. SYMPHOS ELECTRIC, Jl. Raya Agarindo No. 10, Kel. Bunder, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    destinationCity: 'Bandung',
    destinationAddress: 'Komplek Gardu Induk Bandung Selatan 150/20kV, Moh Toha Km 6.5, Bandung',
    currentLocation: {
      city: 'Purwakarta',
      province: 'Jawa Barat',
      landmark: 'Tol Cipularang KM 88 (Tanjakan Purbaleunyi)',
      lat: -6.6134,
      lng: 107.4121,
      speedKmH: 30,
      lastUpdatedAt: '2026-09-04 00:50',
    },
    distanceKm: 140,
    remainingKm: 55,
    isDelayed: false,
    preDeliveryInspection: {
      bushingCondition: 'Good',
      radiatorCondition: 'Good',
      conservatorCondition: 'Good',
      accessoriesCondition: 'Complete',
      oilLeakage: false,
      rustOrDamage: false,
      overallCondition: 'Good',
      inspectedBy: 'QC Bambang H.',
      inspectedAt: '2026-09-03 08:15',
      photos: [],
    },
    trackingHistory: [
      { id: 'tr-02-01', step: 1, status: 'SHIPMENT_CREATED', title: 'Shipment Order Dibuat', timestamp: '2026-09-02 15:00', location: 'Cikupa, Tangerang', updatedBy: 'Admin', role: 'SUPER_ADMIN' },
      { id: 'tr-02-02', step: 7, status: 'DEPARTED', title: 'Berangkat Menuju Bandung', timestamp: '2026-09-03 09:00', location: 'Cikupa, Tangerang', updatedBy: 'Yanto Subagyo', role: 'VENDOR' },
      { id: 'tr-02-03', step: 8, status: 'IN_TRANSIT', title: 'Melintasi Tol Cipularang KM 88', timestamp: '2026-09-04 00:50', location: 'Purwakarta', updatedBy: 'Yanto Subagyo', role: 'VENDOR' },
    ],
    documents: [],
    photos: [],
    activityLogs: [
      { id: 'act-02-01', user: 'Admin', role: 'SUPER_ADMIN', action: 'Membuat shipment SHP-2026-0802', timestamp: '2026-09-02 15:00' },
    ],
  },
  {
    id: 'SHP-2026-0803',
    deliveryOrderNo: 'DO-2026-0943',
    salesOrderNo: 'SO-2026-0420',
    poNumber: 'PO-PHR-RIAU-99',
    transformerId: 'trf-03',
    transformer: initialTransformers[2],
    customerId: 'cust-03',
    customer: initialCustomers[2],
    vendorId: 'ven-09',
    vendor: initialVendors[8],
    driverId: 'drv-09',
    driver: initialDrivers[8],
    vehicleId: 'veh-09',
    vehicle: initialVehicles[8],
    currentStatus: 'DELAYED',
    shipmentDate: '2026-09-01',
    departureDate: '2026-09-01 10:00',
    expectedDeliveryDate: '2026-09-03 18:00', // Overdue! ETA was yesterday evening
    originCity: 'Tangerang',
    originAddress: 'PT. SYMPHOS ELECTRIC, Jl. Raya Agarindo No. 10, Kel. Bunder, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    destinationCity: 'Duri, Riau',
    destinationAddress: 'Main Substation GS-4, Camp Duri Km 12, Mandau, Bengkalis, Riau',
    currentLocation: {
      city: 'Pelabuhan Bakauheni / Merak',
      province: 'Lampung',
      landmark: 'Antrean Dermaga Eksekutif Bakauheni',
      lat: -5.8711,
      lng: 105.7523,
      speedKmH: 0,
      lastUpdatedAt: '2026-09-04 00:30',
    },
    distanceKm: 1250,
    remainingKm: 890,
    isDelayed: true,
    delayMinutes: 450, // 7.5 hours delay
    delayReason: 'Antrean kapal Ro-Ro di penyeberangan Selat Sunda terkendala cuaca buruk & gelombang tinggi 3 meter.',
    delayActionTaken: 'Vendor telah berkoordinasi dengan ASDP untuk prioritas muatan kargo alat berat vital PLN/Pertamina pada keberangkatan kapal berikutnya pukul 04:00 WIB.',
    preDeliveryInspection: {
      bushingCondition: 'Good',
      radiatorCondition: 'Good',
      conservatorCondition: 'Good',
      accessoriesCondition: 'Complete',
      oilLeakage: false,
      rustOrDamage: false,
      overallCondition: 'Good',
      inspectedBy: 'QC Inspector',
      inspectedAt: '2026-09-01 09:00',
      photos: [],
    },
    trackingHistory: [
      { id: 'tr-03-01', step: 1, status: 'SHIPMENT_CREATED', title: 'Shipment Dibuat', timestamp: '2026-08-31 10:00', location: 'Cikupa, Tangerang', updatedBy: 'Admin', role: 'SUPER_ADMIN' },
      { id: 'tr-03-02', step: 7, status: 'DEPARTED', title: 'Berangkat ke Bakauheni', timestamp: '2026-09-01 10:00', location: 'Cikupa, Tangerang', updatedBy: 'Wawan Gunawan', role: 'VENDOR' },
      { id: 'tr-03-03', step: 8, status: 'DELAYED', title: 'Delay Terdeteksi: Cuaca Buruk Selat Sunda', timestamp: '2026-09-03 18:00', location: 'Bakauheni', updatedBy: 'Fauzi Rahman (CKB)', role: 'VENDOR', notes: 'Kapal fery ditunda sementara oleh otoritas pelabuhan akibat gelombang tinggi.' },
    ],
    documents: [],
    photos: [],
    activityLogs: [
      { id: 'act-03-01', user: 'Fauzi Rahman (CKB)', role: 'VENDOR', action: 'Melaporkan kendala cuaca buruk penyeberangan Bakauheni', timestamp: '2026-09-03 18:30' },
    ],
  },
  {
    id: 'SHP-2026-0804',
    deliveryOrderNo: 'DO-2026-0938',
    salesOrderNo: 'SO-2026-0401',
    poNumber: 'PO-KP-2026-112',
    transformerId: 'trf-04',
    transformer: initialTransformers[3],
    customerId: 'cust-04',
    customer: initialCustomers[3],
    vendorId: 'ven-03',
    vendor: initialVendors[2],
    driverId: 'drv-03',
    driver: initialDrivers[2],
    vehicleId: 'veh-03',
    vehicle: initialVehicles[2],
    currentStatus: 'COMPLETED',
    shipmentDate: '2026-08-28',
    departureDate: '2026-08-28 09:00',
    expectedDeliveryDate: '2026-08-29 15:00',
    actualDeliveryDate: '2026-08-29 14:15',
    originCity: 'Tangerang',
    originAddress: 'PT. SYMPHOS ELECTRIC, Jl. Raya Agarindo No. 10, Kel. Bunder, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    destinationCity: 'Cilegon',
    destinationAddress: 'Kawasan Industri Krakatau Steel, Jl. Asia Raya, Cilegon, Banten',
    currentLocation: {
      city: 'Cilegon',
      province: 'Banten',
      landmark: 'Substation Krakatau Posco',
      lat: -6.0022,
      lng: 106.0125,
      lastUpdatedAt: '2026-08-29 15:30',
    },
    distanceKm: 165,
    remainingKm: 0,
    isDelayed: false,
    preDeliveryInspection: {
      bushingCondition: 'Good',
      radiatorCondition: 'Good',
      conservatorCondition: 'Good',
      accessoriesCondition: 'Complete',
      oilLeakage: false,
      rustOrDamage: false,
      overallCondition: 'Good',
      inspectedBy: 'QC Budianto',
      inspectedAt: '2026-08-28 08:15',
      photos: [],
    },
    pod: {
      actualArrivalDate: '2026-08-29',
      actualArrivalTime: '14:15',
      receiverName: 'Wahyudi Santoso',
      receiverPosition: 'Lead Electrical Engineer Krakatau Posco',
      receiverPhone: '+62 812-9800-4411',
      deliveryNotes: 'Trafo TRF-1600-004 diterima dalam kondisi baik tanpa cacat fisik. Bushing dan aksesoris lengkap.',
      deliveryCondition: 'Good / Sempurna',
      signatureUrl: 'https://api.dicebear.com/7.x/shapes/svg?seed=signature-wahyudi',
      podDocumentUrl: '#',
      photos: [
        { title: 'Berita Acara Serah Terima (BAST)', url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80' },
        { title: 'Trafo Posisi Dudukan Foundation', url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80' },
      ],
      submittedAt: '2026-08-29 15:30',
      submittedBy: 'Bambang Irawan (Driver Dunex)',
    },
    trackingHistory: [
      { id: 'tr-04-01', step: 1, status: 'SHIPMENT_CREATED', title: 'Shipment Dibuat', timestamp: '2026-08-27 10:00', location: 'Cikarang', updatedBy: 'Admin', role: 'SUPER_ADMIN' },
      { id: 'tr-04-02', step: 7, status: 'DEPARTED', title: 'Berangkat ke Cilegon', timestamp: '2026-08-28 09:00', location: 'Cikarang', updatedBy: 'Bambang Irawan', role: 'VENDOR' },
      { id: 'tr-04-03', step: 11, status: 'ARRIVED', title: 'Tiba di Lokasi Krakatau Posco', timestamp: '2026-08-29 13:45', location: 'Cilegon', updatedBy: 'Bambang Irawan', role: 'VENDOR' },
      { id: 'tr-04-04', step: 12, status: 'UNLOADING', title: 'Unloading ke Substation B', timestamp: '2026-08-29 14:00', location: 'Cilegon', updatedBy: 'Bambang Irawan', role: 'VENDOR' },
      { id: 'tr-04-05', step: 13, status: 'DELIVERED', title: 'Diterima Customer', timestamp: '2026-08-29 14:15', location: 'Cilegon', updatedBy: 'Wahyudi Santoso', role: 'MARKETING' },
      { id: 'tr-04-06', step: 14, status: 'POD_UPLOADED', title: 'POD & BAST Diunggah', timestamp: '2026-08-29 15:30', location: 'Cilegon', updatedBy: 'Bambang Irawan', role: 'VENDOR' },
      { id: 'tr-04-07', step: 15, status: 'COMPLETED', title: 'Siklus Pengiriman Selesai', timestamp: '2026-08-29 16:00', location: 'System', updatedBy: 'Admin', role: 'SUPER_ADMIN' },
    ],
    documents: [],
    photos: [],
    activityLogs: [
      { id: 'act-04-01', user: 'Admin', role: 'SUPER_ADMIN', action: 'Menutup status pengiriman ke COMPLETED', timestamp: '2026-08-29 16:00' },
    ],
  },
  {
    id: 'SHP-2026-0805',
    deliveryOrderNo: 'DO-2026-0944',
    salesOrderNo: 'SO-2026-0428',
    poNumber: 'PO-SIG-TUBAN-22',
    transformerId: 'trf-05',
    transformer: initialTransformers[4],
    customerId: 'cust-05',
    customer: initialCustomers[4],
    vendorId: 'ven-05',
    vendor: initialVendors[4],
    driverId: 'drv-05',
    driver: initialDrivers[4],
    vehicleId: 'veh-05',
    vehicle: initialVehicles[4],
    currentStatus: 'IN_TRANSIT',
    shipmentDate: '2026-09-02',
    departureDate: '2026-09-02 21:00',
    expectedDeliveryDate: '2026-09-04 18:00',
    originCity: 'Tangerang',
    originAddress: 'PT. SYMPHOS ELECTRIC, Jl. Raya Agarindo No. 10, Kel. Bunder, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    destinationCity: 'Tuban',
    destinationAddress: 'Gardu Induk Pabrik Tuban 4, Desa Sumberarum, Kerek, Tuban, Jatim',
    currentLocation: {
      city: 'Rembang',
      province: 'Jawa Tengah',
      landmark: 'Jalur Pantura Km 112 (Dekat Batas Jateng-Jatim)',
      lat: -6.7051,
      lng: 111.3412,
      speedKmH: 42,
      lastUpdatedAt: '2026-09-04 01:05',
    },
    distanceKm: 580,
    remainingKm: 95,
    isDelayed: false,
    preDeliveryInspection: {
      bushingCondition: 'Good',
      radiatorCondition: 'Good',
      conservatorCondition: 'Good',
      accessoriesCondition: 'Complete',
      oilLeakage: false,
      rustOrDamage: false,
      overallCondition: 'Good',
      inspectedBy: 'QC Sukardi',
      inspectedAt: '2026-09-02 19:30',
      photos: [],
    },
    trackingHistory: [
      { id: 'tr-05-01', step: 1, status: 'SHIPMENT_CREATED', title: 'Shipment Dibuat', timestamp: '2026-09-02 14:00', location: 'Cikupa, Tangerang', updatedBy: 'Admin', role: 'SUPER_ADMIN' },
      { id: 'tr-05-02', step: 7, status: 'DEPARTED', title: 'Berangkat ke Tuban', timestamp: '2026-09-02 21:00', location: 'Cikupa, Tangerang', updatedBy: 'Kuswanto Mulyadi', role: 'VENDOR' },
      { id: 'tr-05-03', step: 8, status: 'IN_TRANSIT', title: 'Melintasi Pantura Rembang', timestamp: '2026-09-04 01:05', location: 'Rembang', updatedBy: 'Kuswanto Mulyadi', role: 'VENDOR' },
    ],
    documents: [],
    photos: [],
    activityLogs: [],
  },
  {
    id: 'SHP-2026-0806',
    deliveryOrderNo: 'DO-2026-0945',
    salesOrderNo: 'SO-2026-0430',
    poNumber: 'PO-JB-CKR-001',
    transformerId: 'trf-06',
    transformer: initialTransformers[5],
    customerId: 'cust-06',
    customer: initialCustomers[5],
    vendorId: 'ven-06',
    vendor: initialVendors[5],
    driverId: 'drv-06',
    driver: initialDrivers[5],
    vehicleId: 'veh-06',
    vehicle: initialVehicles[5],
    currentStatus: 'ARRIVED',
    shipmentDate: '2026-09-03',
    departureDate: '2026-09-03 14:00',
    expectedDeliveryDate: '2026-09-03 18:00',
    actualDeliveryDate: '2026-09-03 17:40',
    originCity: 'Tangerang',
    originAddress: 'PT. SYMPHOS ELECTRIC, Jl. Raya Agarindo No. 10, Kel. Bunder, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    destinationCity: 'Cikarang',
    destinationAddress: 'Power Plant & Substation Estate 3, Jababeka Industrial Park, Cikarang',
    currentLocation: {
      city: 'Cikarang',
      province: 'Jawa Barat',
      landmark: 'Gerbang Substation Jababeka 3',
      lat: -6.2891,
      lng: 107.1623,
      speedKmH: 0,
      lastUpdatedAt: '2026-09-03 23:30',
    },
    distanceKm: 18,
    remainingKm: 0,
    isDelayed: false,
    preDeliveryInspection: {
      bushingCondition: 'Good',
      radiatorCondition: 'Good',
      conservatorCondition: 'Good',
      accessoriesCondition: 'Complete',
      oilLeakage: false,
      rustOrDamage: false,
      overallCondition: 'Good',
      inspectedBy: 'QC Hendri',
      inspectedAt: '2026-09-03 12:00',
      photos: [],
    },
    trackingHistory: [
      { id: 'tr-06-01', step: 1, status: 'SHIPMENT_CREATED', title: 'Shipment Dibuat', timestamp: '2026-09-03 10:00', location: 'Cikupa, Tangerang', updatedBy: 'Admin', role: 'SUPER_ADMIN' },
      { id: 'tr-06-02', step: 7, status: 'DEPARTED', title: 'Berangkat ke Lokasi Jababeka', timestamp: '2026-09-03 14:00', location: 'Cikupa, Tangerang', updatedBy: 'Hadi Sucipto', role: 'VENDOR' },
      { id: 'tr-06-03', step: 11, status: 'ARRIVED', title: 'Tiba di Substation Jababeka', timestamp: '2026-09-03 17:40', location: 'Jababeka Estate 3', updatedBy: 'Hadi Sucipto', role: 'VENDOR', notes: 'Menunggu proses lifting crane pagi hari pukul 08:00 WIB sesuai jadwal tim sipil customer.' },
    ],
    documents: [],
    photos: [],
    activityLogs: [],
  },
  {
    id: 'SHP-2026-0807',
    deliveryOrderNo: 'DO-2026-0946',
    salesOrderNo: 'SO-2026-0435',
    poNumber: 'PO-VALE-SLW-88',
    transformerId: 'trf-10',
    transformer: initialTransformers[9],
    customerId: 'cust-07',
    customer: initialCustomers[6],
    vendorId: 'ven-08',
    vendor: initialVendors[7],
    driverId: 'drv-08',
    driver: initialDrivers[7],
    vehicleId: 'veh-08',
    vehicle: initialVehicles[7],
    currentStatus: 'IN_TRANSIT',
    shipmentDate: '2026-08-30',
    departureDate: '2026-08-31 08:00',
    expectedDeliveryDate: '2026-09-06 17:00',
    originCity: 'Tangerang',
    originAddress: 'PT. SYMPHOS ELECTRIC, Jl. Raya Agarindo No. 10, Kel. Bunder, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    destinationCity: 'Sorowako',
    destinationAddress: 'Smelter Substation #3, Jl. Inco, Magani, Nuha, Luwu Timur, Sulsel',
    currentLocation: {
      city: 'Makassar ke Malili',
      province: 'Sulawesi Selatan',
      landmark: 'Jalan Poros Palopo-Wotu Km 45',
      lat: -2.7123,
      lng: 120.8912,
      speedKmH: 35,
      lastUpdatedAt: '2026-09-04 00:15',
    },
    distanceKm: 820,
    remainingKm: 145,
    isDelayed: false,
    preDeliveryInspection: {
      bushingCondition: 'Good',
      radiatorCondition: 'Good',
      conservatorCondition: 'Good',
      accessoriesCondition: 'Complete',
      oilLeakage: false,
      rustOrDamage: false,
      overallCondition: 'Good',
      inspectedBy: 'Marine Surveyor PT Kamadjaja',
      inspectedAt: '2026-08-30 16:00',
      photos: [],
    },
    trackingHistory: [
      { id: 'tr-07-01', step: 1, status: 'SHIPMENT_CREATED', title: 'Shipment Multimoda Dibuat', timestamp: '2026-08-29 11:00', location: 'Cikupa, Tangerang', updatedBy: 'Admin', role: 'SUPER_ADMIN' },
      { id: 'tr-07-02', step: 8, status: 'IN_TRANSIT', title: 'Melintasi Poros Palopo-Wotu', timestamp: '2026-09-04 00:15', location: 'Sulawesi Selatan', updatedBy: 'Sugeng Riyadi', role: 'VENDOR' },
    ],
    documents: [],
    photos: [],
    activityLogs: [],
  },
  {
    id: 'SHP-2026-0808',
    deliveryOrderNo: 'DO-2026-0947',
    salesOrderNo: 'SO-2026-0440',
    poNumber: 'PO-PLN-JBT-092',
    transformerId: 'trf-07',
    transformer: initialTransformers[6],
    customerId: 'cust-01',
    customer: initialCustomers[0],
    vendorId: 'ven-04',
    vendor: initialVendors[3],
    currentStatus: 'WAITING_PICKUP',
    shipmentDate: '2026-09-04',
    expectedDeliveryDate: '2026-09-05 15:00',
    originCity: 'Tangerang',
    originAddress: 'PT. SYMPHOS ELECTRIC, Jl. Raya Agarindo No. 10, Kel. Bunder, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    destinationCity: 'Bekasi',
    destinationAddress: 'Gardu Induk Cikarang Utama 150kV, Jl. Industri Raya No. 4, Cikarang',
    currentLocation: {
      city: 'Tangerang',
      province: 'Banten',
      landmark: 'Pabrik PT. SYMPHOS ELECTRIC Loading Yard',
      lat: -6.1837769,
      lng: 106.548519,
      lastUpdatedAt: '2026-09-03 16:00',
    },
    distanceKm: 85,
    remainingKm: 85,
    isDelayed: false,
    preDeliveryInspection: {
      bushingCondition: 'Good',
      radiatorCondition: 'Good',
      conservatorCondition: 'Good',
      accessoriesCondition: 'Complete',
      oilLeakage: false,
      rustOrDamage: false,
      overallCondition: 'Good',
      inspectedBy: 'QC Factory',
      inspectedAt: '2026-09-03 15:00',
      photos: [],
    },
    trackingHistory: [
      { id: 'tr-08-01', step: 1, status: 'SHIPMENT_CREATED', title: 'Shipment Dibuat', timestamp: '2026-09-03 14:00', location: 'Cikupa, Tangerang', updatedBy: 'Firhan Roebini', role: 'MARKETING' },
      { id: 'tr-08-02', step: 2, status: 'WAITING_PICKUP', title: 'Menunggu Pengambilan Pos Logistik', timestamp: '2026-09-03 16:00', location: 'Cikupa, Tangerang', updatedBy: 'Agus Setiawan', role: 'VENDOR' },
    ],
    documents: [],
    photos: [],
    activityLogs: [],
  },
  {
    id: 'SHP-2026-0809',
    deliveryOrderNo: 'DO-2026-0948',
    salesOrderNo: 'SO-2026-0442',
    poNumber: 'PO-AMNT-NTB-44',
    transformerId: 'trf-08',
    transformer: initialTransformers[7],
    customerId: 'cust-08',
    customer: initialCustomers[7],
    vendorId: 'ven-07',
    vendor: initialVendors[6],
    currentStatus: 'SHIPMENT_CREATED',
    shipmentDate: '2026-09-04',
    expectedDeliveryDate: '2026-09-09 17:00',
    originCity: 'Tangerang',
    originAddress: 'PT. SYMPHOS ELECTRIC, Jl. Raya Agarindo No. 10, Kel. Bunder, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    destinationCity: 'Sumbawa Barat',
    destinationAddress: 'Main Step-Up Substation Batu Hijau, Sekongkang, Sumbawa Barat, NTB',
    currentLocation: {
      city: 'Tangerang',
      province: 'Banten',
      landmark: 'Pabrik PT. SYMPHOS ELECTRIC Warehouse',
      lat: -6.1837769,
      lng: 106.548519,
      lastUpdatedAt: '2026-09-04 00:00',
    },
    distanceKm: 640,
    remainingKm: 640,
    isDelayed: false,
    preDeliveryInspection: {
      bushingCondition: 'Good',
      radiatorCondition: 'Good',
      conservatorCondition: 'Good',
      accessoriesCondition: 'Complete',
      oilLeakage: false,
      rustOrDamage: false,
      overallCondition: 'Good',
      inspectedBy: 'QC Cikupa Hub',
      inspectedAt: '2026-09-03 17:00',
      photos: [],
    },
    trackingHistory: [
      { id: 'tr-09-01', step: 1, status: 'SHIPMENT_CREATED', title: 'Shipment Order Terdaftar', timestamp: '2026-09-04 00:00', location: 'Cikupa, Tangerang', updatedBy: 'Admin', role: 'SUPER_ADMIN' },
    ],
    documents: [],
    photos: [],
    activityLogs: [],
  },
  {
    id: 'SHP-2026-0810',
    deliveryOrderNo: 'DO-2026-0949',
    salesOrderNo: 'SO-2026-0445',
    poNumber: 'PO-PLN-JBT-101',
    transformerId: 'trf-09',
    transformer: initialTransformers[8],
    customerId: 'cust-02',
    customer: initialCustomers[1],
    vendorId: 'ven-10',
    vendor: initialVendors[9],
    currentStatus: 'WAITING_PICKUP',
    shipmentDate: '2026-09-04',
    expectedDeliveryDate: '2026-09-06 12:00',
    originCity: 'Tangerang',
    originAddress: 'PT. SYMPHOS ELECTRIC, Jl. Raya Agarindo No. 10, Kel. Bunder, Kec. Cikupa, Kabupaten Tangerang, Banten 15710',
    destinationCity: 'Bandung',
    destinationAddress: 'Komplek Gardu Induk Bandung Selatan 150/20kV, Bandung',
    currentLocation: {
      city: 'Tangerang',
      province: 'Banten',
      landmark: 'Outbound Bay PT. SYMPHOS ELECTRIC',
      lat: -6.1837769,
      lng: 106.548519,
      lastUpdatedAt: '2026-09-04 01:00',
    },
    distanceKm: 140,
    remainingKm: 140,
    isDelayed: false,
    preDeliveryInspection: {
      bushingCondition: 'Good',
      radiatorCondition: 'Good',
      conservatorCondition: 'Good',
      accessoriesCondition: 'Complete',
      oilLeakage: false,
      rustOrDamage: false,
      overallCondition: 'Good',
      inspectedBy: 'QC Cikupa',
      inspectedAt: '2026-09-03 18:00',
      photos: [],
    },
    trackingHistory: [
      { id: 'tr-10-01', step: 1, status: 'SHIPMENT_CREATED', title: 'Shipment Dibuat', timestamp: '2026-09-03 18:00', location: 'Cikupa, Tangerang', updatedBy: 'Admin', role: 'SUPER_ADMIN' },
      { id: 'tr-10-02', step: 2, status: 'WAITING_PICKUP', title: 'Menunggu Penugasan Driver Berdikari', timestamp: '2026-09-04 01:00', location: 'Cikupa, Tangerang', updatedBy: 'Arif Wibowo', role: 'VENDOR' },
    ],
    documents: [],
    photos: [],
    activityLogs: [],
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'Keterlambatan Terdeteksi (Delayed)',
    message: 'Shipment SHP-2026-0803 (Tujuan Duri Riau) melewati batas ETA akibat kendala penyeberangan Bakauheni.',
    type: 'delay',
    shipmentId: 'SHP-2026-0803',
    timestamp: '2026-09-03 18:05',
    isRead: false,
  },
  {
    id: 'notif-02',
    title: 'Trafo Tiba di Lokasi Customer',
    message: 'Shipment SHP-2026-0806 telah tiba di Gardu Induk Jababeka Estate 3.',
    type: 'info',
    shipmentId: 'SHP-2026-0806',
    timestamp: '2026-09-03 17:40',
    isRead: false,
  },
  {
    id: 'notif-03',
    title: 'Proof of Delivery (POD) Selesai',
    message: 'Shipment SHP-2026-0804 telah diserahterimakan dan BAST bertandatangan telah diunggah oleh Krakatau Posco.',
    type: 'success',
    shipmentId: 'SHP-2026-0804',
    timestamp: '2026-08-29 15:35',
    isRead: true,
  },
  {
    id: 'notif-04',
    title: 'Pembaruan Posisi Live Tracking',
    message: 'Driver Sutrisno (PT Samudera Trans) melaporkan posisi di KM 57 Tol Cikampek untuk SHP-2026-0801.',
    type: 'info',
    shipmentId: 'SHP-2026-0801',
    timestamp: '2026-09-04 01:15',
    isRead: false,
  },
];

export const initialActivityLogs: ActivityLogItem[] = [
  {
    id: 'log-01',
    user: 'Sutrisno Waluyo',
    role: 'VENDOR',
    action: 'Memperbarui lokasi dan milestone IN_TRANSIT untuk SHP-2026-0801',
    details: 'Lokasi: Rest Area KM 57 Tol Japek. Kecepatan 38 km/h. Kondisi trafo aman.',
    timestamp: '2026-09-04 01:15:22',
  },
  {
    id: 'log-02',
    user: 'Fauzi Rahman',
    role: 'VENDOR',
    action: 'Memperbarui kendala keterlambatan cuaca buruk di Bakauheni untuk SHP-2026-0803',
    details: 'Status beralih ke DELAYED otomatis (ETA Terlewati).',
    timestamp: '2026-09-03 18:30:10',
  },
  {
    id: 'log-03',
    user: 'Lismaya Sari',
    role: 'MARKETING',
    action: 'Mengunduh laporan performa pengiriman kuartal Q3 (Excel Format)',
    timestamp: '2026-09-03 16:45:00',
  },
  {
    id: 'log-04',
    user: 'Hendra Gunawan',
    role: 'VENDOR',
    action: 'Menetapkan armada Tronton Lowbed B 9821 UXT dan Driver Sutrisno untuk SHP-2026-0801',
    timestamp: '2026-09-02 17:30:00',
  },
  {
    id: 'log-05',
    user: 'Jodi Setiawan',
    role: 'SUPER_ADMIN',
    action: 'Membuat shipment order baru SHP-2026-0801 (TRF-3000-001 ke GI Cikarang Utama)',
    timestamp: '2026-09-02 14:00:00',
  },
];
